adobe/aem-cif-guides-venia

ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/miniaccount/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/structure/.content.xml, ui.frontend/README.md, ui.frontend/clientlib.config.js, ui.frontend/package.json, ui.frontend/pom.xml, ui.frontend/src/main/components/App/App.js, ui.frontend/src/main/components/App/config.js, ui.frontend/src/main/components/App/i18n.js, ui.frontend/src/main/site/styles/header.scss, ui.frontend/src/main/styles/commerce/_navigation.scss, ui.frontend/src/main/webpack/components/commerce/_navigation.scss, ui.frontend/src/main/webpack/site/styles/header.scss, ui.frontend/webpack.common.js, ui.frontend/webpack.dev.js
**_This PR requires PR (https://github.com/adobe/aem-cif-guides-venia/pull/7) to be merged first_**
This PR is to add `miniaccount` component to the header of the venia store, `miniaccount` component defined in this PR will render the core CIF component `miniaccount` defined in `https://github.com/adobe/aem-core-cif-components` on the header, which will then render a container div on the header that can be used as the mount point by `account dropdown` React component.
* https://github.com/adobe/aem-core-cif-components/issues/303
* Internal ref: CIF-1444 and CIF-1445
This PR is required as it adds the ability to render core CIF component `miniaccount` on the header of venia storefront so that the `account dropdown` React component can use the `<div>` container rendered by `miniaccount` CIF …
=> CIF-1444: Add 'miniaccount' component to the header of page templates in venia storefront

README.md, ui.apps/src/main/content/jcr_root/apps/venia/config.publish/org.apache.sling.jcr.resource.internal.JcrResourceResolverFactoryImpl.xml
Document usage of CIF best practices, disable sling mapping by default
CIF-1505
n/a
=> CIF-1505 - 

ui.apps/src/main/content/jcr_root/apps/venia/components/button/.content.xml
Use the correct resource super-type for the button component.
CIF-1525
=> CIF-1525 - use correct super type for button component

pom.xml
Set latest released versions for components and magento graphql
=> @trivial: bump versions for components and magento graphql

README.md, pom.xml
- update SDK dependency version
- add a dedicated profile for the release:prepare goal
=> CIF-1574 - Release Venia store demo on Github

ui.frontend/src/main/components/App/App.js, ui.frontend/src/main/components/App/config.js
* Uses new `ConfigContext` to provide configuration to all components in the React tree.
* Uses new `Portal` component to render components at different mounting points.
This requires a new release of the CIF components before it can be merged.
* Manual testing
=> CIF-1546 - Pass the DOM nodes in which the components render as props

ui.frontend/src/main/components/App/App.js, ui.frontend/src/main/components/App/config.js
The initial change will be reapplied after a new release of CIF components
https://github.com/adobe/aem-cif-guides-venia/pull/33 was merged by mistake. 
The change requires new CIF components release.
=> CIF-1546: Revert merged PR 33

pom.xml, ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/breadcrumb/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/structure/.content.xml, ui.content/src/main/content/jcr_root/content/venia/language-masters/en/.content.xml, ui.content/src/main/content/jcr_root/content/venia/us/en/.content.xml, ui.frontend/src/main/styles/_breadcrumb.scss, ui.frontend/src/main/styles/commerce/_breadcrumb.scss
- creates `breadcrumb` proxy component
- adds breadcrumb to appropriate templates
Manually tested.
=> CIF-1540 - CIF breadcrumb component

ui.frontend/README.md
See https://github.com/adobe/aem-core-cif-components/pull/380.
=> CIF-1548 - Add customization instructions for CSS template

pom.xml, ui.frontend/package-lock.json, ui.frontend/package.json
=> @releng - adjusting dependency versions before release

.circleci/ci/it-tests.js, it.tests/src/main/java/com/venia/it/tests/CategoryPageIT.java, it.tests/src/main/java/com/venia/it/tests/LandingPageIT.java, it.tests/src/main/java/com/venia/it/tests/ProductPageIT.java, it.tests/src/main/java/com/venia/it/tests/SearchPageIT.java
To be merged AFTER we release and update the version of the CIF Components to include the new breadcrumb component.
=> CIF-1500 - Setup IT project for Venia Demo

ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml
- replace no longer existing productlist clientlib with productcollection
=> CIF-1640 - Productcollection clientlib is not included in Venia demo

ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/initial/.content.xml, ui.frontend/src/main/styles/commerce/_productlist.scss
- adding css for the "load more" button and loading spinner
- fix bug that productlist component is not added to the initial content of the category-page
See https://github.com/adobe/aem-core-cif-components/pull/406 for screenshots.
=> CIF-1609 - Lazy Loading for PLP

.circleci/config.yml, ui.frontend/package-lock.json
- update cloud SDK image version
- Fix integrity hash for package.json
CIF-1651
Integration tests fail for the dataLayer features. 
see https://git.corp.adobe.com/CQ/quickstart/commit/fb631ca78dc7678b043356fd57332a9ad1a6515a#diff-d0074d03ff40297194576e50c21439d4
Manually
=> CIF-1651: update cloud SDK image version

ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/xf-web-variation/policies/.content.xml
- add default policies for HTML title tag type for product carousel, related products, and featured category list components, and all templates
When this PR is approved, we'd have to decide if we also want to define these policies in the AEM archetype.
https://github.com/adobe/aem-core-cif-components/pull/410
Manually tested.
=> CIF-1630 - Configurable header tag for teaser and carousel components

pom.xml
* Update CIF Core components dependency to latest 1.4.0 release.
* Update `frontend-maven-plugin` to use Node 12, same versions as components.
=> releng - Prepare Release with CIF Core Components 1.4.0

ui.frontend/package-lock.json, ui.frontend/package.json
* Update CIF Core React components dependency to latest 1.4.0 release.
=> releng - Prepare Release with CIF Core Components 1.4.0 (React Components)

core/src/main/java/com/venia/core/models/commerce/MyProductTeaserImpl.java, core/src/test/java/com/venia/core/models/commerce/MyProductTeaserImplTest.java, it.tests/src/main/java/com/venia/it/tests/CategoryPageIT.java, it.tests/src/main/java/com/venia/it/tests/ProductPageIT.java, it.tests/src/main/java/com/venia/it/tests/SearchPageIT.java, it.tests/src/main/java/com/venia/it/utils/Utils.java, it.tests/src/main/resources/datalayer/grouped-product.json, it.tests/src/main/resources/datalayer/placeholder-category-items.json, it.tests/src/main/resources/datalayer/placeholder-product.json, it.tests/src/main/resources/datalayer/sample-category-gallery.json, it.tests/src/main/resources/datalayer/sample-category-items.json, it.tests/src/main/resources/datalayer/sample-searchresult-gallery.json, it.tests/src/main/resources/datalayer/sample-searchresult-items.json, it.tests/src/main/resources/datalayer/simple-product.json, pom.xml, ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/productteaser/productteaser.html, ui.content/src/main/content/jcr_root/conf/venia/.content.xml, ui.content/src/main/content/jcr_root/content/venia/.content.xml
If the dataLayer feature is enabled, this will render the JSON payload for MyTeaser component
CIF-1181
Feature is being merged in Core CIF Components as well
unit tests
=> Enable dataLayer on custom component

all/pom.xml, pom.xml, ui.config/pom.xml
Fixed maven auto install package
CIF-1697
maven auto install package stoped working after introducing classifiers
manually
=> CIF-1697: Fix maven package auto install

ui.config/src/main/content/jcr_root/apps/venia/osgiconfig/config/com.adobe.cq.commerce.graphql.client.impl.GraphqlClientImpl~default.cfg.json
* added cache configuration for navigation, search and breadcrumb components
CIF-1752
Manually.
=> CIF-1752 - Add default cache configuration for Venia

ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/catalogpage/customfooterlibs.html, ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/catalogpage/customheaderlibs.html, ui.apps/src/main/content/jcr_root/apps/venia/components/footer/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/template-types/page/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/structure/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/structure/.content.xml, ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/footer/master/.content.xml, ui.tests/pom.xml, ui.tests/test-module/package.json
* updated footer experience fragment
* changed footer to experience fragment based footer in page templates
* removed footer proxy component
CIF-1501
Manually.
=> CIF-1501 - XF based page footer with authoring support

pom.xml
=> @relend Update the `aem-core-cif-components` dependency to version 1.6.0

ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/footer/master/.content.xml, ui.frontend/src/main/site/styles/footer.scss
* fixed the background color, margins, copyright formatting of the XF footer
* removed unused styling
CIF-1772
manually
=> CIF-1772 - Fix footer styling in Venia demo

ui.apps/src/main/content/jcr_root/apps/venia/components/page/customheaderlibs.html
* fixed clientlib inclusion
https://github.com/adobe/aem-core-cif-components/pull/477
CIF-1849
Manually.
=> CIF-1849 - Create minimal default styling for product carousel

ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml
Include category carousel default styles in cif clientlib.
CIF-1906
Manually.
=> CIF-1906 - Minimal default styling for category carousel

it.tests/src/main/resources/datalayer/grouped-product.json, it.tests/src/main/resources/datalayer/placeholder-product.json, it.tests/src/main/resources/datalayer/simple-product.json, pom.xml
Adapted ITs for recent dataLayer changes
CIF-1952
Recent changes in the product dataLayer info needs ITs adaptation
Integration tests
=> CIF-1952: Fix dataLayer related ITs

core/pom.xml, ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/products/.content.xml, ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/products/promotions/.content.xml, ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/products/promotions/master/.content.xml, ui.content/src/main/content/jcr_root/content/venia/language-masters/en/products/product-page/.content.xml, ui.content/src/main/content/jcr_root/content/venia/us/en/products/product-page/.content.xml
Add sample PDP XF and placeholder for Venia, see screenshot.
CIF-1943
Show usage of dynamic Experience Fragments for PDP in Venia
=> CIF-1943 - add sample PDP XF and placeholder for Venia

pom.xml, ui.frontend/src/main/styles/commerce/_productteaser.scss
* fixed product name and price background for product teaser
CIF-2019
Manually.
=> CIF-2019 - Venia product teaser text rendering issue

.circleci/ci/it-tests.js, pom.xml
- update graphql dependency to 2.4.2 EE to align with CIF components
=> CIF-1718 - Adopt Magento GraphQL schema changes - Category UID

.circleci/config.yml
* Use new Docker images which use Azul Zulu JDK for builds and testing
* CircleCI build passes
=> CIF-2015 - Migrate to Azul Zulu JDK

pom.xml
- @trivial - update dependencies
=> dependency

pom.xml, ui.frontend/package-lock.json, ui.frontend/package.json
Update `AEM Core CIF Components` to 1.11.0 and `@adobe/aem-core-cif-react-components` to 1.11.0
=> @releng Update dependency versions

.circleci/config.yml, ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/category-page-reverse/.content.xml, ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/category-page/.content.xml
Update sample URL mappings to adapt for UID and URL_PATH for category pages
CIF-2032
Needed for when URLProvider is configured to work with URL_PATH in Skyline
Manually in RegexR
=> CIF-2032: Category page mapping for UID + URL_PATH

ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/policies/.content.xml, ui.frontend/src/main/styles/_contentfragment.scss
Add sample styles for commerce CF component
CIF-2140
=> CIF-2140 - add sample styles for commerce CF

ui.frontend/src/main/components/App/App.js
Read the custom HTTP headers from the DOM attribute and pass them to the ConfigurationContext
CIF-2097
Functional testing
=> CIF-2097 - Consume the configured values in MagentoGraphqlClient and Config Exporters

core/src/main/java/com/venia/core/models/commerce/MyProductTeaserImpl.java, core/src/test/java/com/venia/core/models/commerce/MyProductTeaserImplTest.java
This adapts Venia to the CIF 2.0 api surface, removing implementations of the deprecated API and its usage in tests.
CIF-2137
=> CIF-2137: Remove implementation of deprecated API

all/pom.xml, core/pom.xml, pom.xml, ui.apps/pom.xml, ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/productrecommendations/.content.xml
Added product recs proxy component 
CIF-2143
Enable product recommendations
Manually
=> CIF-2143: Create Product Recommendations AEM component

ui.apps/src/main/content/jcr_root/apps/venia/components/button/.content.xml
Uses the Button V2 introduced in https://github.com/adobe/aem-core-cif-components/pull/615 for Venia
CIF-2153
=> CIF-2153 - use Button component V2

ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml, ui.frontend/src/main/styles/commerce/_navigation.scss
Use the default styling of navigation component in Venia.
CIF-1926
Manually.
=> CIF-1926 - Minimal default styling for navigation

ui.content/src/main/content/jcr_root/conf/venia/_sling_configs/.content.xml, ui.frontend/.eslintignore
Add default config for rendering storefront context data
CIF-2222
Product recs
unit test
=> CIF-2222: Add config for storefront context render

pom.xml
=> Update the graphql-client 1.7.4

it.tests/src/main/resources/datalayer/placeholder-category-items.json
With CIF-2334 we removed the SKUs from the product list placeholder data causing the CategroyPageIT to fail. This PR fixes the expected test data in the integration tests.
CIF-2334 (cause)
CIF-2385
IT
=> CIF-2385: remove skus from placeholder data in categrory page it

ui.content/src/main/content/jcr_root/content/dam/venia/.content.xml
* Remove `asset.jpg` node from XML which does not exist.
=> trivial - Remove empty asset.jpg node

ui.frontend/package-lock.json, ui.frontend/package.json
In order to prevent incompatibilities of peer dependencies for projects that want to make use of peregrine and the CIF react-components we must align our dependencies.
CIF-2345
CIF-2246
unit tests, integration tests
=> CIF-2345: update dependencies to meet the ones of peregrine

ui.tests/test-module/specs/venia/content-fragment-component-dialog.js, ui.tests/test-module/specs/venia/searchbar.js
Fixed UI test failure on Skyline instance.
CIF-2382
UI test.
=> CIF-2382 - Content Fragment Component Dialog test fails against Skyline instance

pom.xml, ui.frontend/package-lock.json, ui.frontend/package.json
update CIF components to 2.2.0
n/a
=> releng - update CIF components to 2.2.0

ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/category-page-reverse/.content.xml, ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/category-page/.content.xml, ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/product-page-reverse/.content.xml, ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/product-page/.content.xml
update /etc/map configs to work with PLP/PDP url suffix
CIF-2432
=> CIF-2432 - update /etc/map configs to work with url suffix

ui.frontend/src/main/components/App/App.js, ui.frontend/src/main/components/App/config.js
With CIF-2292 the body.html overwrite in the cif core components page got removed and the store configuration is now exported as a meta tag. This PR uses the new location of the configuration.
It also updates other paths in the pagePath set to be relative to the base path.
CIF-2292
Integration Tests
=> CIF-2292: update access to the store configuration for react components

pom.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/xf-web-variation/policies/.content.xml, ui.frontend/package-lock.json, ui.frontend/package.json
This PR is a replacement for the approved and verified PR which was opened by mistake for "main" instead of "dev":
https://github.com/adobe/aem-cif-guides-venia/pull/220
=> CIF-2195 - Add additional recommendation types #220

pom.xml, ui.frontend/package-lock.json, ui.frontend/package.json
… latest
updated CIF components version and GraphQL Client version to latest
=> releng - updated CIF components version and GraphQL Client version to latest

ui.tests/Dockerfile, ui.tests/docker-compose-wdio-chrome.yaml, ui.tests/docker-compose-wdio-firefox.yaml, ui.tests/pom.xml, ui.tests/test-module/specs/venia/react.js
Fix Venia ui.tests running via mvn
CIF-2585
=> CIF-2585 - fix Venia ui.tests running via mvn

ui.frontend/i18n/en.json, ui.frontend/src/main/components/CartPage/ProductListing/__tests__/__snapshots__/product.spec.js.snap, ui.frontend/src/main/components/CartPage/ProductListing/product.js, ui.frontend/src/main/components/MiniCart/ProductList/__tests__/__snapshots__/item.spec.js.snap, ui.frontend/src/main/components/MiniCart/ProductList/__tests__/__snapshots__/productList.spec.js.snap, ui.frontend/src/main/components/MiniCart/ProductList/__tests__/item.spec.js, ui.frontend/src/main/components/MiniCart/ProductList/__tests__/productList.spec.js, ui.frontend/src/main/components/MiniCart/ProductList/index.js, ui.frontend/src/main/components/MiniCart/ProductList/item.js, ui.frontend/src/main/components/MiniCart/ProductList/productList.js, ui.frontend/src/main/components/MiniCart/miniCart.js, ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/__tests__/__snapshots__/item.spec.js.snap, ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/__tests__/__snapshots__/items.spec.js.snap, ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/__tests__/__snapshots__/orderDetails.spec.js.snap, ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/__tests__/item.spec.js, ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/__tests__/items.spec.js, ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/__tests__/orderDetails.spec.js, ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/index.js, ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/item.js, ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/items.js, ui.frontend/src/main/components/OrderHistoryPage/OrderDetails/orderDetails.js, ui.frontend/src/main/components/OrderHistoryPage/__tests__/__snapshots__/orderRow.spec.js.snap, ui.frontend/src/main/components/OrderHistoryPage/__tests__/orderHistoryPage.spec.js, ui.frontend/src/main/components/OrderHistoryPage/__tests__/orderRow.spec.js, ui.frontend/src/main/components/OrderHistoryPage/orderHistoryPage.js, ui.frontend/src/main/components/OrderHistoryPage/orderRow.js
* Removed broken product links from the following components:
* Minicart
* Cart
* Order History
Updated unit tests
=> CIF-2563 - Remove broken product links from cart and order history

ui.frontend/i18n/en.json, ui.frontend/package-lock.json, ui.frontend/package.json, ui.frontend/src/main/components/App/App.js, ui.frontend/src/main/components/Header/accountTrigger.js, ui.frontend/src/main/components/Peregrine/__tests__/useToastEvents.spec.js, ui.frontend/src/main/components/Peregrine/useToastEvents.js
* Added `ToastContainer` component from Venia UI which displays toasts.
* Created new `useToastEvents` hook which listens to toast events and triggers toasts.
* Added unit tests.
Also see https://github.com/adobe/aem-core-cif-components/pull/788.
=> CIF-2603 - Add visual indication for add to wishlist

ui.tests/README.md
See CIF-2508 for more information.
=> CIF-2508 - Move secrets from Zerobin to Vault

ui.config/src/main/content/jcr_root/apps/venia/osgiconfig/config/com.adobe.cq.commerce.core.components.internal.services.UrlProviderImpl.cfg.json
This enables context-aware product urls for Venia. It also changes the product page url format to use the `url_path`. This is necessary to encode category information in the URLs.
CIF-2503
https://github.com/adobe/aem-core-cif-components/pull/785
Integration and UI tests
=> CIF-2503: update url provider configuration to use new features

pom.xml, ui.frontend/package-lock.json, ui.frontend/package.json
* Update CIF Core Components version to 2.5.0
=> releng - Update CIF Core Components version to 2.5.0

ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml, ui.frontend/src/main/styles/commerce/_navigation.scss
* Removed clientlib from the CIF Core Navigation v2 component
* Added those styles to the `ui.frontend` module to be included by `clientlib-site`.
* Manually
=> CIF-2638 - Move navigation styling to Venia

pom.xml, ui.tests/test-module/specs/venia/productlist-dialog.js
Added UI test for product list edit dialog.
CIF-2519
UI test.
=> CIF-2519 - Support category filter for product list component

README.md
compare with https://github.com/adobe/aem-core-cif-components/issues/825#issuecomment-1041246330
=> Fix link for URL configuration

README.md
- fix readme links to old wiki
- replace CIF Connector usage with Commerce Add-On
* https://github.com/adobe/aem-core-cif-components/issues/825
* CIF-2695
=> CIF-2695 - fix readme links & wording

README.md, ui.tests/test-module/specs/venia/component-dialogs.js, ui.tests/test-module/specs/venia/productcarousel-dialog.js
Added UI test for product carousel component dialog.
CIF-2672
UI test.
=> CIF-2672 - Support category filter for product carousel component

pom.xml
Update jacoco to the latest release.
=> CIF-2725: support newer Java versions

ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/searchresults/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/policies/.content.xml, ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/policies/.content.xml, ui.frontend/src/main/styles/commerce/_productcarousel.scss, ui.frontend/src/main/styles/commerce/_productcollection.scss, ui.tests/test-module/specs/venia/component-dialogs.js, ui.tests/test-module/specs/venia/productcarousel-dialog.js
* updated UI test for product carousel and related products component dialog
* added styling for 'Add to Cart' and 'Add to Wish List' buttons in product carousel and product collection
* enabled 'Add to Cart' button by default for productlist and searchresults component
CIF-2526
UI tests, manually
=> CIF-2526 - Add add-to-cart button in all product collections

ui.tests/test-module/specs/venia/commerce-page-dialogs.js
* added UI tests for commerce page properties (landing, category, product pages)
CIF-2766
UI tests.
=> CIF-2766 - Commerce property tab for category template page is broken

it.tests/src/main/java/com/venia/it/tests/CategoryPageIT.java, it.tests/src/main/resources/datalayer/sample-category-items.json, pom.xml, ui.content/src/main/content/jcr_root/content/venia/language-masters/en/search/.content.xml, ui.content/src/main/content/jcr_root/content/venia/us/en/search/.content.xml, ui.tests/test-module/specs/venia/component-dialogs.js, ui.tests/test-module/specs/venia/productlist-dialog.js
Updated UI tests for productlist and searchresults edit dialog.
CIF-2736
Manually, UI tests.
=> CIF-2736 - Support custom sort keys in product listing components

ui.tests/test-module/specs/venia/component-dialogs.js, ui.tests/test-module/specs/venia/productcarousel-dialog.js
* updated UI tests for productcarousel, relatedproducts, categorycarousel and  featuredcategories component
CIF-2727
Manually, UI tests.
=> CIF-2727 - Category Carousel: add option to open CTA in a new Tab

ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/catalogpage/.content.xml, ui.apps/src/main/content/jcr_root/apps/venia/components/page/.content.xml
Use the CIF v3 page for Venia.
CIF-2289
=> CIF-2289: update Venia to use v3 page

ui.tests/test-module/lib/wdio.commands.js, ui.tests/test-module/specs/venia/commerceteasser-dialog.js, ui.tests/test-module/specs/venia/component-dialogs.js
Added UI tests for the commerce teaser dialog features.
CIF-2884
UI tests.
=> CIF-2884 - Commerce teaser dialog clientlib regressions

ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/teaser/.content.xml, ui.apps/src/main/content/jcr_root/apps/venia/components/teaser/.content.xml, ui.tests/test-module/lib/wdio.commands.js, ui.tests/test-module/specs/venia/commerceteasser-dialog.js, ui.tests/test-module/specs/venia/component-dialogs.js
* enabled commerce teaser v3 and wcm teaser v2 in proxy components
* improved UI test for commerce teaser
CIF-2732
Manually, UI tests.
=> CIF-2732 - Teaser: add option to open CTA in a new Tab

ui.frontend/src/main/styles/commerce/_product.scss
Uses the newly introduced class modifiers for product options to style the color swatch list
CIF-2836
Adds the ability to better style the product options tiles (colors, sizes, etc).
Manually
=> CIF-2836: Update swatch color style

ui.tests/test-module/lib/wdio.commands.js, ui.tests/test-module/specs/venia/commerceteasser-dialog.js
* enabled UI test disabled earlier for CIF-2884
CIF-2850, CIF-2884
UI test.
=> CIF-2850 - 2022.06.0 Release Post Actions

ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml, ui.frontend/src/main/styles/commerce/_product.scss
Use v3 of product component 
CIF-2885
Enable selective rendering of product sections
Manually
=> CIF-2885: Use v3 of product component

ui.tests/test-module/specs/venia/commerce-page-dialogs.js
* Add UI tests for https://github.com/adobe/aem-core-cif-components/pull/935
=> CIF-2841 - Allow content pages to be associated with products and categories

pom.xml
* set CIF components dependency to snapshot version after release
=> CIF-2937 - 2022.08.0 Release Post Actions

it.tests/src/main/resources/datalayer/placeholder-category-items.json, it.tests/src/main/resources/datalayer/sample-category-items.json, it.tests/src/main/resources/datalayer/sample-searchresult-items.json
Fixing some ITs related to the changes made to datalayer with the newly introduced Experience Platform Connector.
=> fix: Integration Tests failing on datalayer assertions

pom.xml, ui.frontend/package-lock.json, ui.frontend/package.json
* updated to CIF components 2.12.4
=> SITES-17835 - Release CIF Components 2.12.4

pom.xml, ui.frontend/package-lock.json, ui.frontend/package.json
* updated dependencies to CIF Components 2.13.0
=> SITES-22114 - Release new CIF components version 2.13.0

.circleci/config.yml, pom.xml, ui.frontend/package-lock.json, ui.frontend/package.json, ui.tests/test-module/package.json, ui.tests/test-module/specs/venia/commerceteasser-dialog.js
=> Sync dev to main before release

ui.frontend/src/main/components/CheckoutPage/OrderConfirmationPage/__tests__/__snapshots__/orderConfirmationPage.spec.js.snap, ui.frontend/src/main/components/CheckoutPage/OrderConfirmationPage/orderConfirmationPage.js
=> SITES-15054: Resolves the missing order no issue

pom.xml, ui.frontend/package-lock.json, ui.frontend/package.json
updates CIF components dependency to 2.14.2
=> @releng - updated CIF components dependency to 2.14.2

pom.xml, ui.frontend/i18n/en.json, ui.frontend/package-lock.json, ui.frontend/package.json, ui.frontend/src/main/components/CheckoutPage/OrderConfirmationPage/__tests__/__snapshots__/orderConfirmationPage.spec.js.snap, ui.frontend/src/main/components/CheckoutPage/OrderConfirmationPage/orderConfirmationPage.js
=> Sync dev to main before release 

all/pom.xml, classic/all/pom.xml, classic/dispatcher/pom.xml, classic/ui.config/pom.xml, classic/ui.content/pom.xml, core/pom.xml, dispatcher/pom.xml, it.tests/pom.xml, pom.xml, ui.apps.structure/pom.xml, ui.apps/pom.xml, ui.config/pom.xml, ui.content/pom.xml, ui.frontend/pom.xml, ui.tests/pom.xml
=> Merges Main branch to dev  after release

pom.xml, ui.frontend/package-lock.json, ui.frontend/package.json
=> @releng - updated CIF components dependency to 2.15.0

all/pom.xml, classic/all/pom.xml, classic/dispatcher/pom.xml, classic/ui.config/pom.xml, classic/ui.content/pom.xml, core/pom.xml, dispatcher/pom.xml, it.tests/pom.xml, pom.xml, ui.apps.structure/pom.xml, ui.apps/pom.xml, ui.config/pom.xml, ui.content/pom.xml, ui.frontend/pom.xml, ui.tests/pom.xml
=> Merges Main branch to dev after release 

.circleci/config.yml
* updates the docker image, browser tools and node
=> @releng - fix circleci issue with old docker image (#345)

it.tests/src/main/resources/datalayer/grouped-product-65.json, it.tests/src/main/resources/datalayer/grouped-product.json, it.tests/src/main/resources/datalayer/simple-product-65.json, it.tests/src/main/resources/datalayer/simple-product.json
=> SITES-31757: Updates the commerce DNS changes

pom.xml
=> Reverts the core-cif.component version

pom.xml, ui.frontend/package-lock.json, ui.frontend/package.json
* updated Core WCM Components version to 2.19.0
=> SITES-26261 - Test CIF compatibility with AEM 6.5 LTS

.circleci/ci/it-tests.js, pom.xml, ui.frontend/package-lock.json, ui.frontend/package.json
=> @releng - updated CIF Components to 2.17.2
