.circleci/ci/deploy-venia.js
all/pom.xml
pom.xml
ui.apps.structure/pom.xml
ui.apps/pom.xml
ui.content/pom.xml

This PR adds Maven classifiers to all the content packages that will have `cloud` or `classic` specific content. This ensures that, for example, the `all` module creates a different artefact for each profile:
- `venia.all-1.0.0-SNAPSHOT-cloud.zip` for the cloud profile (or when not specifying any profile)
- `venia.all-1.0.0-SNAPSHOT-classic.zip` for the classic profile
This is mainly useful to ensure that the `all` package doesn't include a content package built for a different profile.
I also fixed the deploy script so that we will release both `all` content packages (that is, `-cloud` and `-classic`) when doing a release.
Locally tested with both profiles.

CIF-1490 - Add maven classifiers to Venia content packages

---

ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-cif/.content.xml

* The CIF React components are added to Venia via the `ui.frontend` module and the `clientlib-base`. The dependency specified in `clientlib-cif` is a duplication and needs to be removed.
* Manually tested

trivial - Remove CIF React clientlib from clientlib-cif

---

.circleci/ci/it-tests.js
.circleci/config.yml

This sets up the jobs to run integration tests. I didn't consider the "Cloud SDK test without Add-On" because this is already checked by the CIF components integration tests and it is not a valid deployment case for the demo.
I checked the logs of the AEM instance for each test: everything is installed correctly. The next step is to add integration tests.

CIF-1499 - Setup IT infrastructure for Venia Demo

---

ui.frontend/src/main/components/App/App.js
ui.frontend/src/main/components/App/config.js

* Moved `Cart` component into a `Portal` component, to make it resilient against a missing `#minicart` container.
* I tested that removing the DOM containers of any of the components does not break the other ones.
* Manual tested

CIF-1591 - Missing portal container breaks all React components

---

ui.content/src/main/content/filter-templates/filter-classic.xml
ui.content/src/main/content/filter-templates/filter-cloud.xml

* Updated filter mode of templates to `update` to properly add new nodes on upgrade. 
* This in particular fixes an issue where the `miniaccount` node was not correctly added to the `header` in templates.
* Manually tested.
* Install an older version of Venia that for example doesn't have the `miniaccount` nodes yet (e.g. https://github.com/adobe/aem-cif-guides-venia/tree/de00a556cfcd1d41a5a3d1bdffd2ab96ed398941).
* Install the latest Venia release and see that some `miniaccount` are not added.

CIF-1592 - Update filter mode for templates to fix upgrades

---

.circleci/config.yml
.github/codecov.yml
README.md

* Added CIF Core components to build on all branches except `main`. By default the `master` branch is used. If there exists a branch with the same name, it will be checked out instead.
* Fixed `codecov.yml` and ignore coverage of all dependencies.
* Explained branching strategy in README.

CIF-1625 Setup dev branch with snapshot dependencies

---

ui.frontend/package-lock.json
ui.frontend/package.json

Remove unnecessary @magento/peregrine dependency
CIF-1635
@magento/peregrine was removed from React Core CIF https://github.com/adobe/aem-core-cif-components/pull/418
Manual UI test

CIF-1635: Remove @magento/peregrine dependency

---

ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/policies/.content.xml
ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/catalog-page/policies/.content.xml
ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/category-page/policies/.content.xml
ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/landing-page/policies/.content.xml
ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/page-content/policies/.content.xml
ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/product-page/policies/.content.xml
ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/root-page/policies/.content.xml
ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/templates/xf-web-variation/policies/.content.xml
ui.frontend/src/main/styles/_teaser.scss
ui.frontend/src/main/styles/teaser/_banner-dark.scss
ui.frontend/src/main/styles/teaser/_banner-light.scss
ui.frontend/src/main/styles/teaser/_feature-left.scss
ui.frontend/src/main/styles/teaser/_feature-right.scss

Add commerce teaser styles & corresponding policies to add 4 predefined styles that can be used by authors.
The PR added 4 sample styles:
* Banner - light
* Banner - dark
* Feature - left
* Feature - right
CIF-1673
Component should have some default styling.
manually

CIF-1673 - add commerce teaser styles & corresponding policies

---

ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/teaser/.content.xml
ui.frontend/src/main/styles/_teaser.scss

* updated commerce teaser to latest Core WCM teaser
* user commerce teaser name consistently
CIF-1678 
Manually.

CIF-1678 - Commerce Teaser should align HTL files with WCM core component

---

ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/experiencefragment/.content.xml
ui.apps/src/main/content/jcr_root/apps/venia/components/xfpage/_cq_dialog/.content-cloud.xml

- Add commerce experience fragment proxy component
New component provided by https://github.com/adobe/aem-core-cif-components/pull/458
- Also adds the configuration to set the fragment location
Manually tested.

CIF-1512 - Dynamic XF on PDP

---

.circleci/ci/it-tests.js
pom.xml
ui.tests/test-module/lib/commons.js
ui.tests/test-module/lib/wdio.commands.js
ui.tests/test-module/specs/venia/component-dialogs.js

* Adding some additional UI tests which check that components can be used in the Sites editor and that their dialogs work.
* Added CIF Connector to the IT test setup, otherwise the product and category picker fields don't work on AEM 6.5.
* Updated dependency to CIF core components to 1.6.1-SNAPSHOT to include the Commerce Experience Fragment component.
Tests run on CircleCI for 6.5 and AEMaaCS.

CIF-1674 - Add UI tests for component dialogs

---

ui.apps/src/main/content/jcr_root/apps/venia/components/xfpage/_cq_dialog/.content-cloud.xml

This adds category references to experience fragments when the project is built with the cloud profile
The feature allows users to associate experience fragments to categories and display a list of existing category associations with that XF.
The table below the category picker shows associations and the edit icon in each row should take user to the category properties page. 
Manual testing

CIF-1818: Category reference tab + picker for Experience Fragments

---

ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/experiencefragment/.content.xml
ui.apps/src/main/content/jcr_root/apps/venia/components/xfpage/_cq_dialog/.content-cloud.xml
ui.tests/test-module/specs/venia/component-dialogs.js

Update CIF XF component name and dialog field label. Related to https://github.com/adobe/aem-core-cif-components/pull/482
CIF-1931, CIF-1932
n/a

CIF-1931, CIF-1932 - rename component and XF properties field

---

ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/footer/master/.content.xml
ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/header/master/.content.xml
ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/products/promotions/master/.content.xml

Add the missing `cq:lastModified` property to the master variations of the sample experience fragments
CIF-1958

CIF-1958 - Add missing cq:lastModified property to sample XF in Venia

---

.circleci/config.yml
ui.tests/test-module/specs/venia/catalog-page-dialogs.js

Added UI test for catalog page properties extensions.
CIF-2039
UI test.

CIF-2039 - Missing root category field in catalog page properties

---

.circleci/config.yml
ui.tests/test-module/lib/commons.js

* Set `affinity` cookie when doing requests using the `request` library. The cookie is otherwise normally added for operations within the browser.
* The cookie is required for testing against AEMaaCS environments (not SDK) with multiple instances. Setting the cookie allows the test to run all requests against the same instance.

CIF-2065 - Set affinity cookie for all requests in WDIO tests

---

ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/experiencefragment/.content.xml
ui.tests/test-module/specs/venia/component-dialogs.js

Changed title of commerce experience fragment component to "Commerce Experience Fragment".
CIF-2135
Manually.

CIF-2135 - Rename component to "Commerce Experience Fragment"

---

ui.tests/test-module/specs/venia/content-fragment-component-dialog.js

Add waitUntil block for flaky check.
Improve stability of UI test.
CIF-2154

CIF-2154 - Improve UI tests for commerce content fragment component

---

ui.apps/src/main/content/jcr_root/apps/venia/components/page/.content.xml

Implement specific category support using `urlPath` (in the page properties) instead of `uidAndUrlPath`. Relates to https://github.com/adobe/aem-core-cif-components/pull/620
CIF-2193

CIF-2193 - use CIF page V2 component

---

core/src/test/java/com/venia/core/models/commerce/MyProductTeaserImplTest.java

Since we use injector specific annotations the current mock context is not precisely replicating runtime behaviour anymore. This PR fixes issues where the mock context differs from the runtime to support injector specific sling models annotations.
CIF-2210 (url provider injected from sling bindings instead of osgi service registry)
CIF-2188 (adapter missing for WCM CC Component)
Unit tests

CIF-2210: adapt unit tests to provide mocks for injector specific annotations

---

dispatcher-cloud/src/conf.d/rewrites/rewrite.rules
dispatcher-cloud/src/conf.dispatcher.d/filters/filters.any
ui.config/src/main/content/jcr_root/apps/venia/osgiconfig/config.publish/org.apache.sling.sitemap.impl.SitemapScheduler~default.cfg.json
ui.content/src/main/content/jcr_root/content/venia/us/en/.content.xml
ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/.content.xml
ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/account-details/.content.xml
ui.content/src/main/content/jcr_root/content/venia/us/en/my-account/address-book/.content.xml
ui.content/src/main/content/jcr_root/content/venia/us/en/products/category-page/.content.xml
ui.content/src/main/content/jcr_root/content/venia/us/en/products/product-page/.content.xml
ui.content/src/main/content/jcr_root/content/venia/us/en/reset-password/.content.xml
ui.content/src/main/content/jcr_root/content/venia/us/en/search/.content.xml

This PR adds default sitemap configurations to venia to:
- generate a default sitemap at the homepage (us/en)
- exclude all the account pages from it (robots noindex)
- generate a product and category sitemap
CIF-2251
Manual

CIF-2251: adds sitemap configurations

---

ui.frontend/src/main/styles/commerce/_productteaser.scss

* Added dark background to product teaser name and price text to achieve a higher contrast ratio on bright backgrounds (> 5.0).
* The style is inspired from the [Commerce Teaser](https://aemcomponents.dev/content/core-components-examples/library/commerce/teaser.html) component.
* Closes https://github.com/adobe/aem-core-cif-components/issues/682.

CIF-2368 - Increase contrast ratio for product teaser title and price

---

pom.xml

Update the release tag name format to match the names we used before we aligned our maven setup with wknd.
CIF-2512
I ran a release:prepare locally without pushing and validated the git messages and git tag name.

CIF-2512: set tag name format to match the previous tag names

---

.circleci/ci/deploy-venia.js
.circleci/config.yml
pom.xml
ui.tests/pom.xml

This enables the deployment of the Venia cloud artefacts to maven central to be reused by others. Classic artefacts were excluded to "save space" and execution time as there is no use case for them (yet). However they are still built and uploaded to github.
CIF-2160
1) I deployed the last release tag to a staging repository and dropped it afterwards
1) I enabled deploy-sample job for this branch and run it once deploying a snapshot to ossrh

CIF-2458: deploy venia cloud artefacts to maven central

---

.circleci/ci/it-tests.js
it.tests/pom.xml
it.tests/src/main/java/com/venia/it/tests/CategoryPageIT.java
it.tests/src/main/java/com/venia/it/tests/ProductPageIT.java
it.tests/src/main/java/junit/category/IgnoreOn65.java
it.tests/src/main/java/junit/category/IgnoreOnCloud.java

In this PR the assertions made to the page metadata for product and category pages were made dependent on the environment the test is executed again (6.5.8 or cloud). This is because the APIs used to generate the canonical link are different for on-prem 6.5.8 and cloud:
- 6.5.8 uses the Externalizer, creating a external author link as canonical url in the tests
- cloud uses the Sites SEO API without any sling mapping, returning the page path of products/categories as is
The implementation is done the same way as we run it already for the CIF Core Components, however we default to IngoreOnCloud as exclude category to not cause any issues for CM builds.
CIF-2511, CIF-2262
Locally, CI

CIF-2511: use target dependent assertions in integration tests

---

.gitignore
ui.frontend/package.json

Removes the `rm` command from the `i18n:extract-compile` script in order to retain compatibility with non unix-like systems like windows.
#238

fix: remove `rm` command from i18n:extract-compile

---

.circleci/config.yml

We want to keep our internal staging environment(s) up to date with the latest Venia release. This change adds another step to the CI workflow which updates the CM repository with the latest Venia release tag.
CIF-2114
Some test runs on CircleCI to validate the script execution using the latest release tag. Note: the expected outcome would be a rejected push as we already merged venia-2021-12-01 before.
https://app.circleci.com/pipelines/github/adobe/aem-cif-guides-venia/1148/workflows/702fb05e-bb57-494d-b279-30ed0b78db00/jobs/5253

CIF-2114: Update Cloud Manager repositories for each release

---

ui.config/src/main/content/jcr_root/apps/venia/osgiconfig/config.publish/org.apache.sling.jcr.resource.internal.JcrResourceResolverFactoryImpl.cfg.json
ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/.content.xml
ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/category-page/.content.xml
ui.content/src/main/content/jcr_root/etc/map.publish/https/hostname.adobeaemcloud.com/product-page/.content.xml

Canonical link generation does not fully work on Cloud Service. We only have mappings for product/category pages in etc/map. This change moves the path mapping for all pages also to etc/map in order to generate absolute urls for content as well. 
CIF-1675, 
CIF-2646
Sitemaps, canonical links
locally

CIF-2646: move /content/venia => / mapping to etc/map

---

ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/catalogpage/customheaderlibs.html

* fixed HTL syntax in catalogpage customheaderlibs.html
CIF-2678
Manually.

CIF-2678 - Styling is broken on catalog page in Venia and archetype projects

---

.circleci/config.yml

* Replaced Azul JDK images with legacy ones using OpenJDK. Cannot use the new CircleCI OpenJDK images yet, since our `ui.frontend` project needs Python which is not part of the new images.
* Adapted to new pattern to install browsers for UI testing via `circleci/browser-tools` orb, since they are no longer included in the images.
Via CircleCI

releng - Replace Azul JDK with OpenJDK images

---

pom.xml

With this change we move parts of frontend-maven-plugin configuration to the parent module to reduce duplication. We also update the version to the latest release.
CIF-2811
https://github.com/eirslett/frontend-maven-plugin/pull/970
Support builds on Apple Silicon with node versions older than 16
Build locally, CI

CIF-2811: update frontend-maven-plugin

---

ui.tests/test-module/specs/venia/commerce-page-dialogs.js

* Added E2E tests for https://github.com/adobe/aem-core-cif-components/pull/885
* Tests require changes from the add-on, so they might fail until the new release is out.

CIF-2757 - Add UI tests for tracking annotations for product and category filters in page properties

---

all/pom.xml
all/src/main/content/META-INF/vault/filter.xml
all/src/main/content/jcr_root/apps/venia/osgiconfig-cloud/config.author/com.adobe.cq.commerce.graphql.client.impl.GraphqlClientImpl~venia.cfg.json
all/src/main/content/jcr_root/apps/venia/osgiconfig-cloud/config.publish/com.adobe.cq.commerce.graphql.client.impl.GraphqlClientImpl~venia.cfg.json

This change adds the GraphqlClient configuration that we already had as example with caching enabled for classic, to AEMaaCS.  
The configuration can be considered as a recommendation and starting point.
The configuration is added to the cloud container package `all`, in order to not introduce another artefact to the reactor. Currently the `ui.config` and `classic/ui.config` packages are both deployed by the `classic/all` container.  
CIF-2919

CIF-2919: add gql client cache configuration for cloud

---

ui.apps/src/main/content/jcr_root/apps/venia/clientlibs/clientlib-base/.content.xml

With embedding the datalayer clientlib we duplicate the javascript on the page, causing all cmp:clicks to be tracked twice.
This change removes the embed. Now the datalayer clientlib is only loaded async by the page v3 component we use.
CIF-2865

CIF-2865: remove duplicated datalayer clientlib

---

core/src/main/java/com/venia/core/models/commerce/MyProductTeaserImpl.java
pom.xml

* Added example of how to extend the product filter via retriever in `MyProductTeaser`. The added filter does not have any impact when using the Venia product catalog.
Requires a release of https://github.com/adobe/commerce-cif-magento-graphql/pull/29 before it can be merged.
See 
* https://github.com/adobe/commerce-cif-magento-graphql/pull/27
* https://github.com/adobe/aem-core-cif-components/pull/938
Manually tested.

CIF-2895 - Add example for product filter hook

---

ui.content/src/main/content/jcr_root/conf/venia/settings/wcm/policies/.content.xml
ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/products/productlist-content/.content.xml
ui.content/src/main/content/jcr_root/content/experience-fragments/venia/us/en/site/products/productlist-content/master/.content.xml
ui.content/src/main/content/jcr_root/content/venia/language-masters/en/products/category-page/.content.xml
ui.content/src/main/content/jcr_root/content/venia/us/en/products/category-page/.content.xml
ui.frontend/src/main/styles/commerce/_productlist.scss
ui.tests/test-module/specs/venia/productlist-dialog.js

Added example usage of XF placeholder in productlist
CIF-2827
Manually

CIF-2827: Add produclist XF example

---

pom.xml
ui.apps/src/main/content/jcr_root/apps/venia/components/commerce/list/.content.xml
ui.apps/src/main/content/jcr_root/apps/venia/components/list/.content.xml
ui.tests/test-module/specs/venia/component-dialogs.js

* added proxy component for commerce list
* added UI test for commerce list edit dialog
CIF-2842
Manually, UI tests.

CIF-2842 - Extend List component to list pages by product or category

---

classic/all/pom.xml

Removed GraphQL client from ALL package for AEM 6.5.
CIF-2953

CIF-2953 - Remove graphql client from Venia classic all package

---

classic/ui.config/src/main/content/jcr_root/apps/venia/osgiconfig-classic/config.author/com.adobe.granite.resourcestatus.impl.CompositeStatusType~editor.config.cfg.json

Added the Composite Status Type for editor that was moved to the CS quickstart to Venia for classic. 
https://github.com/adobe/aem-core-cif-components/pull/951
https://github.com/adobe/aem-cif-guides-venia/pull/264
Locally, the configuration has a higher priority of the ootb one from /libs

CIF-2946: add cif specific composite status type for editor to classic

---

.circleci/config.yml
core/pom.xml
core/src/main/java/com/venia/core/models/commerce/MySearchResultsImpl.java
core/src/test/java/com/venia/core/models/commerce/MySearchResultsImplTest.java
pom.xml
ui.tests/test-module/specs/venia/productcollection.js

* added custom SearchResults model implementation to illustrate the customization of sort fields
* added unit test
* updated dependency on CIF components
SITES-16602
Manually, junit.

SITES-16602 - Remove sort by position option in the Search Results Component

---

.circleci/config.yml
core/src/main/java/com/venia/core/models/commerce/MySearchResultsImpl.java
core/src/test/java/com/venia/core/models/commerce/MyProductTeaserImplTest.java
core/src/test/java/com/venia/core/models/commerce/MySearchResultsImplTest.java
it.tests/src/main/resources/datalayer/grouped-product-65.json
it.tests/src/main/resources/datalayer/grouped-product.json
it.tests/src/main/resources/datalayer/simple-product-65.json
it.tests/src/main/resources/datalayer/simple-product.json

@releng - fix pipeline issues and tests

---

.circleci/config.yml
classic/dispatcher/src/conf.d/available_vhosts/venia_publish.vhost
classic/dispatcher/src/conf.d/variables/ams_default.vars
core/pom.xml
core/src/main/java/com/venia/core/models/commerce/MySearchResultsImpl.java
core/src/main/java/com/venia/core/models/commerce/services/CommerceComponentModelFinder.java
core/src/main/java/com/venia/core/models/commerce/servlets/CatalogPageErrorFilter.java
core/src/test/java/com/venia/core/models/commerce/MyProductTeaserImplTest.java
core/src/test/java/com/venia/core/models/commerce/MySearchResultsImplTest.java
core/src/test/java/com/venia/core/models/commerce/services/CommerceComponentModelFinderTest.java
core/src/test/java/com/venia/core/models/commerce/servlets/CatalogPageErrorFilterTest.java
dispatcher/src/conf.d/available_vhosts/venia.vhost
dispatcher/src/conf.d/variables/custom.vars
it.tests/src/main/resources/datalayer/grouped-product-65.json
it.tests/src/main/resources/datalayer/grouped-product.json
it.tests/src/main/resources/datalayer/simple-product-65.json
it.tests/src/main/resources/datalayer/simple-product.json
pom.xml
ui.content/src/main/content/jcr_root/content/venia/language-masters/en/errors/503/.content.xml
ui.content/src/main/content/jcr_root/content/venia/us/en/errors/503/.content.xml
ui.frontend/package-lock.json
ui.frontend/package.json

Sync dev to main before release
